parameters:
    auth.event.jwt_response_listener.class: AuthBundle\EventListener\TokenResponseListener
    auth.event.jwt_created_listener.class: AuthBundle\EventListener\TokenCreatedListener
    auth.event.jwt_decoded_listener.class: AuthBundle\EventListener\TokenDecodedListener

services:
    auth.event.jwt_response_listener:
        class: '%auth.event.jwt_response_listener.class%'
        tags:
            -
                name: kernel.event_listener
                event: lexik_jwt_authentication.on_authentication_success
                method: onAuthenticationSuccessResponse

    auth.event.jwt_created_listener:
        class: '%auth.event.jwt_created_listener.class%'
        tags:
            -
                name: kernel.event_listener
                event: lexik_jwt_authentication.on_jwt_created
                method: onCreated

    auth.event.jwt_decoded_listener:
        class: '%auth.event.jwt_decoded_listener.class%'
        tags:
            -
                name: kernel.event_listener
                event: lexik_jwt_authentication.on_jwt_decoded
                method: onDecoded
