services:

    admin.genre:
        class: AppBundle\Admin\GenreAdmin
        arguments:
            - ~
            - AppBundle\Entity\Genre
            - ~
        tags:
            -
                name: sonata.admin
                manager_type: orm
                label: Genres
                group: Genre
                icon: '<i class="fa fa-star-o"></i>'
                label_catalogue: messages

    admin.genrecategory:
        class: AppBundle\Admin\GenreCategoryAdmin
        arguments:
            - ~
            - AppBundle\Entity\GenreCategory
            - ~
        tags:
            -
                name: sonata.admin
                manager_type: orm
                label: Categories
                icon: '<i class="fa fa-star-o"></i>'
                group: Genre
                label_catalogue: messages

    admin.user:
        class: UserBundle\Admin\UserAdmin
        arguments:
            - ~
            - UserBundle\Entity\User
            - ~
        tags:
            -
                name: sonata.admin
                manager_type: orm
                label: Users
                icon: '<i class="fa fa-user"></i>'
                group: User management
                label_catalogue: messages
