api:
    resource: '@AppBundle/Controller/'
    type: rest

user:
    resource: '@UserBundle/Controller/'
    prefix: /user
    type: rest

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix: /doc

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin