api:
    type: rest
    resource: '@AppBundle/Controller/'

user:
    type: rest
    prefix: /user
    resource: '@UserBundle/Controller/'

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /doc
