api:
    type: rest
    resource: '@AppBundle/Controller/'
#    prefix: /api

#auth:
#    resource: '@UserBundle/Controller/'
#    prefix: /api

#api_login_check:
#    path: /api/login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
