api:
    resource: '@AppBundle/Controller/'
    type: rest

user:
    resource: '@UserBundle/Controller/'
    prefix: /user
    type: rest

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix: /doc
