api:
    type: rest
    resource: '@AppBundle/Controller/'
    prefix: /api

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
