api:
    type: rest
    resource: '@AppBundle/Controller/'
    prefix: /api

acme_api:
    resource: "@AcmeApiBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
