security:

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt|doc))/
            security: false

        login:
            pattern:  ^/auth$
            stateless: true
            anonymous: true
            form_login:
                check_path: auth_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api_mutable:
            lexik_jwt: ~
            pattern: ^/
            stateless: true
            methods:
                - DELETE
                - POST
                - PUT

        api_private:
            lexik_jwt: ~
            pattern: ^/user/profile$|^/user/dashboard$
            stateless: true
            methods:
                - GET
            lexik_jwt:
                query_parameter:
                    enabled: true
                    name:    bearer

    access_control:
        - { path: ^/auth$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
