security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    jsiciarek:  { password: pass, roles: [ ROLE_SUPER_ADMIN ] }
                    colak: { password: pass, roles: [ ROLE_ADMIN ] }
                    molak: { password: pass, roles: [ ROLE_USER ] }

    firewalls:
        dev:
            pattern:  ^/api/(_(profiler|wdt|doc))/
            security: false

        login:
            pattern:  ^/api/auth
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/auth
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api_mutable:
            pattern:   ^/api
            stateless: true
            methods:
                - DELETE
                - POST
                - PUT
            lexik_jwt: ~
        api_private:
            pattern:   ^/api/user/(profile|dashboard)|/api/author
            stateless: true
            methods:
                - GET
            lexik_jwt: ~

    access_control:
        - { path: ^/api/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
