security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    jsiciarek:  { password: pass, roles: [ ROLE_SUPER_ADMIN ] }
                    colak: { password: pass, roles: [ ROLE_ADMIN ] }
                    molak: { password: pass, roles: [ ROLE_USER ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt|doc))/
            security: false

        login:
            pattern:  ^/auth$
            stateless: true
            anonymous: true
            form_login:
                check_path: auth_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api_mutable:
            lexik_jwt: ~
            pattern: ^/
            stateless: true
            methods:
                - DELETE
                - POST
                - PUT

        api_private:
            lexik_jwt: ~
            pattern: ^/user/profile$|^/user/dashboard$|^/author
            stateless: true
            methods:
                - GET

    access_control:
        - { path: ^/auth$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
