# http://swagger.io/specification/

nelmio_api_doc:
    documentation:
        info:
            title: Songbook REST Api
            description: Very useful for singing PHP programmers.
            version: 0.0.1
    routes:
        path_patterns: # an array of regexps
            - ^/artist
            - ^/author
            - ^/genre
            - ^/lyrics
            - ^/song
            - ^/user
