parameters:
    knp.doctrine_behaviors.blameable_subscriber.user_entity: Application\Sonata\UserBundle\Entity\User

knp_doctrine_behaviors:
    timestampable:  true
    blameable:      true
    soft_deletable: true
    sortable:       true
