<?php

namespace Tests\AuthBundle;

use AppBundle\Entity\Genre;
use Tests\TestCase;

/**
 * @group genre
 */
class GenreControllerTest extends TestCase
{
    const DUMMY_GENRE_NAME = 'Dummy Genre';

    public static function genreDataProvider()
    {
        return [
            [
                'post_genre',
                [
                    'category' => [
                        'id' => 1,
                        'name' => 'African'
                    ],
                    'name' => self::DUMMY_GENRE_NAME,
                    'description' => self::DUMMY_GENRE_NAME . ' description.',
                    'info' => self::DUMMY_GENRE_NAME . ' info.'
                ]
            ]
        ];
    }

    /**
     * @dataProvider genreDataProvider
     */
    public function testPostAction($route, $data)
    {
        $router = $this->getContainer()->get('router');
        $url = $router->generate($route, [], $router::ABSOLUTE_URL);

        $authHeaders = $this->getAuthHeaders();
        list($resp, $info) = $this->getResponse('post', $url, json_encode($data), $authHeaders);

//        $this->fail($resp);
//        echo $url . PHP_EOL;
//        echo json_encode($authHeaders) . PHP_EOL;
//        echo json_encode($data) . PHP_EOL;

        $rdata = json_decode($resp, true);

        $this->assertArrayHasKey('id', $rdata, $resp);
        $this->assertNotNull($rdata['id'], $resp);
        $this->assertGreaterThan(0, $rdata['id']);
        unset($rdata['id']);
        $this->assertEquals($data, $rdata);
    }

    public function getAuthHeaders() {
        $router = $this->getContainer()->get('router');
        $authUrl = $router->generate('auth_check', [], $router::ABSOLUTE_URL);
        $authData = [
            'username' => 'colak',
            'password' => 'pass',
        ];

        $headers = [
            'Content-Type: application/x-www-form-urlencoded',
        ];
        list($resp, $info) = $this->getResponse('POST', $authUrl, http_build_query($authData), $headers);

        $data = json_decode($resp, true);

        return [
            sprintf('Authorization: Bearer %s', $data['token']),
        ];
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $em = $this->getContainer()->get('doctrine.orm.entity_manager');
        $qb = $em->getRepository(Genre::class)->createQueryBuilder('o')
            ->delete()
            ->andWhere('o.name = :name')
            ->setParameters(['name' => self::DUMMY_GENRE_NAME])
        ;
        $qb->getQuery()->execute();
    }

    public function tearDown()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $em = $this->getContainer()->get('doctrine.orm.entity_manager');
        $qb = $em->getRepository(Genre::class)->createQueryBuilder('o')
            ->delete()
            ->andWhere('o.name = :name')
            ->setParameters(['name' => self::DUMMY_GENRE_NAME])
        ;
        $qb->getQuery()->execute();
    }
}
