services:

    AppBundle\EventListener\SortableSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.acme:
        class: AppBundle\Common\Acme
        calls:
            - [ setContainer, [ '@service_container' ] ]

    app.exception_controller:
        class: AppBundle\Controller\ExceptionController
        arguments:
            - '@twig'
            - '%kernel.debug%'