services:

    AppBundle\EventListener\SortableSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.exception_controller:
        class: AppBundle\Controller\ExceptionController
        arguments:
            - '@twig'
            - '%kernel.debug%'