jms_serializer:
    metadata:
        directories:
            fosuser:
                namespace_prefix: FOS\UserBundle\Model
                path: '%kernel.root_dir%/serializer/FOS/UserBundle/Model'
            user:
                namespace_prefix: Sonata\UserBundle\Model
                path: '%kernel.root_dir%/serializer/Sonata/UserBundle/Model'
            app:
                namespace_prefix: AppBundle\Entity
                path: '%kernel.root_dir%/serializer/AppBundle/Entity'