jms_serializer:
    metadata:
        directories:
            fos_user:
                namespace_prefix: FOS\UserBundle\Model
                path: '%kernel.root_dir%/serializer'
            sonata_user:
                namespace_prefix: Sonata\UserBundle\Model
                path: '%kernel.root_dir%/serializer'
            app_sonata_user:
                namespace_prefix: Application\Sonata\UserBundle\Entity
                path: '%kernel.root_dir%/serializer'
            app:
                namespace_prefix: AppBundle\Entity
                path: '%kernel.root_dir%/serializer'