<?php

namespace AppBundle\Entity;

/**
 * GenreCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
