fos_rest:
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys # Data decoding only
    format_listener: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: 'force'
    serializer:
      serialize_null: true